### ISSUE TITLE
Drag and drop bug

### ISSUE THREAD

**Issue by Maorshl** [amitby98/pre-course-2021-final-boilerplate#1]
when you add or remove a task, Drag and drop pictures in the bottom dont stay in the bright rectangle .

steps to reproduce:
- load the page
- add a couple of tasks

expected result:
images stay in the bright rectangle

actual result:
images a little bit off position.

**Comment by amitby98** [comment]
Hey @Maorshl i'm working on it, thanks!

**Comment by amitby98** [comment]
Hey @Maorshl i fixed the bug, you can checked this out.  
Enjoy and thanks again!😊
